language: node_js
sudo: true

node_js:
  - "9"
  - "8"
  - "6"

python:
  - "2.7"
  - "3.5"

script:
  - npm install
  - npm run test

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

before_script:
  # install nats
  - wget https://github.com/nats-io/gnatsd/releases/download/v1.0.4/gnatsd-v1.0.4-linux-amd64.zip -qO tmp.zip
  - unzip tmp.zip
  - mv gnatsd-v1.0.4-linux-amd64 gnatsd

before_install:
  - chmod +x setup_arangodb.sh
  - ./setup_arangodb.sh

notifications:
  email:
    on_success: never
    on_failure: always
